import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Navbar */}
        <nav>
          <a href="/">Home</a>
          <a href="/shop">Marketplace</a>
          <a href="/invest">Wealth</a>
        </nav>

        {/* Page Content */}
        <main>{children}</main>

        {/* External Script */}
        <Script src="https://qa.interswitchng.com/collections/public/javascripts/inline-checkout.js" strategy="lazyOnload" />
      </body>
    </html>
  );
}
